language: python
python:
- 3.6
- 3.6-dev

# env:
  # global:
  # - MYPYPATH=$(python -c "import sys ; print(sys.prefix, end='')")/lib/python3.6/site-packages
  # python is not yet configured at this point

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7-dev
  - python: 3.6-dev

install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt

before_script:
# - export MYPYPATH=$(python -c "import sys ; print(sys.prefix, end='')")/lib/python3.6/site-packages

script:

- mypy --follow-imports=skip basic-client.py
- prospector basic-client.py
- python basic-client.py

- mypy --follow-imports=skip basic-client-class.py
- prospector basic-client-class.py
- python basic-client-class.py

after_script:
- ls --color $(python -c "import sys ; print(sys.prefix, end='')")/lib/python3.6/site-packages
- pylint basic-client.py
- pylint basic-client-class.py
- mypy --follow-imports=silent basic-client.py
- mypy --follow-imports=silent basic-client-class.py
- find . -name \*.py | xargs grep -l 'CLIENT'
- printenv MYPYPATH
- mypy --follow-imports=skip -p mypy
- unset MYPYPATH
- printenv MYPYPATH
- mypy --follow-imports=skip -p mypy
