language: python
python:
- 3.6
- 3.6-dev

# env:
  # global:
  # - MYPYPATH=$(python -c "import sys ; print(sys.prefix, end='')")/lib/python3.6/site-packages
  # python is not yet configured at this point

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7-dev
  - python: 3.6-dev

install:
- python --version
- pip --version
- python -m pip install --upgrade pip setuptools wheel
- python -m pip install -r requirements.txt
- python -m pip install -r requirements_dev.txt

before_script:
- command -v python
- which python
- command -v python3
- which python3
- command -v mypy
- which mypy
- python -c "import h11"
# - export MYPYPATH=$(python -c "import sys ; print(sys.prefix, end='')")/lib/python3.6/site-packages

script:
- find . -name h11\*
- find $(python -c "import sys ; print(sys.prefix, end='')")/lib/python3.6/site-packages -name h11\*

- python $(command -v mypy) --follow-imports=skip basic-client.py
- python $(which mypy) --follow-imports=skip basic-client.py
- python3 $(command -v mypy) --follow-imports=skip basic-client.py
- python3 $(which mypy) --follow-imports=skip basic-client.py
- mypy --follow-imports=skip basic-client.py
- prospector basic-client.py
- python basic-client.py

- mypy --follow-imports=skip basic-client-class.py
- prospector basic-client-class.py
- python basic-client-class.py

after_script:
- ls --color $(python -c "import sys ; print(sys.prefix, end='')")/lib/python3.6/site-packages
- pylint basic-client.py
- pylint basic-client-class.py
- mypy --follow-imports=silent basic-client.py
- mypy --follow-imports=silent basic-client-class.py
- find . -name \*.py | xargs grep -l 'CLIENT'
- printenv MYPYPATH
- mypy --follow-imports=skip -p mypy
- unset MYPYPATH
- printenv MYPYPATH
- mypy --follow-imports=skip -p mypy
