language: python
python:
- 3.6
- 3.6-dev

env:
- MYPYPATH=$(python -c "import sys ; print(sys.prefix, end='')")/lib/python3.6/site-packages

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.7-dev
  - python: 3.6-dev

install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt

script:

- mypy --ignore-missing-imports basic-client.py
- mypy --follow-imports=skip basic-client.py
- prospector basic-client.py
- python basic-client.py

- mypy --ignore-missing-imports basic-client-class.py
- mypy --follow-imports=skip basic-client-class.py
- prospector basic-client-class.py
- python basic-client-class.py

after_script:
- pylint basic-client.py
- pylint basic-client-class.py
- mypy --follow-imports=silent basic-client.py
- mypy --follow-imports=silent basic-client-class.py
- find . -name \*.py | xargs grep -l 'CLIENT'
- printenv MYPYPATH
